# -*- coding: utf-8 -*-
"""demand_forecasting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pU15m-Abz_x3JZ8Oof3OwJcfSsZCvnHC
"""

!pip -q install xgboost openpyxl joblib


import os
import zipfile
import joblib
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files

from xgboost import XGBRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

warnings.filterwarnings("ignore")

np.random.seed(42)


# ============================================================
# 3. UPLOAD ORIGINAL 1200-ROW EXCEL
# ============================================================

print("Upload your original Excel file")

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

print("\nFile uploaded:", file_name)


# ============================================================
# 4. LOAD DATA
# ============================================================

df = pd.read_excel(file_name)

print("\nDataset loaded!")
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())


# ============================================================
# 5. BASIC VALIDATION
# ============================================================

required_columns = [
    'SKU',
    'DC',
    'historical_avg_demand_units',
    'baseline_weekly_demand',
    'seasonal_amplitude',
    'matched_context_date'
]

missing = [
    col for col in required_columns
    if col not in df.columns
]

if missing:

    raise ValueError(
        f"Missing required columns: {missing}"
    )

print("\nRequired columns verified.")


# ============================================================
# 6. DATE CONVERSION
# ============================================================

date_columns = [
    'mfg_date',
    'receipt_date',
    'expiry_date',
    'matched_context_date'
]

for col in date_columns:

    if col in df.columns:

        df[col] = pd.to_datetime(
            df[col],
            errors='coerce'
        )


# ============================================================
# 7. BASIC DATA INFORMATION
# ============================================================

print("\nUnique SKUs:", df['SKU'].nunique())

print("Unique DCs:", df['DC'].nunique())

print(
    "Context date:",
    df['matched_context_date'].min(),
    "→",
    df['matched_context_date'].max()
)


# ============================================================
# 8. CREATE SKU/DC BASE
# ============================================================

# Only actual SKU/DC combinations
base = (
    df[
        ['SKU', 'DC']
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

print(
    "\nSKU/DC combinations:",
    len(base)
)


# ============================================================
# 9. GET DATE RANGE
# ============================================================

latest_date = (
    df['matched_context_date']
    .max()
)

HISTORY_DAYS = 180

start_date = (
    latest_date
    -
    pd.Timedelta(
        days=HISTORY_DAYS - 1
    )
)

dates = pd.date_range(
    start=start_date,
    end=latest_date,
    freq='D'
)

print(
    "\nDate range:"
)

print(
    start_date.date(),
    "→",
    latest_date.date()
)

print(
    "Number of dates:",
    len(dates)
)


# ============================================================
# 10. CREATE SKU/DC × DATE GRID
# ============================================================

base['_key'] = 1

date_df = pd.DataFrame({
    'date': dates,
    '_key': 1
})

demand_df = (
    base
    .merge(
        date_df,
        on='_key'
    )
    .drop(
        columns=['_key']
    )
)

print(
    "\nDaily base shape:",
    demand_df.shape
)


# ============================================================
# 11. MERGE MASTER FEATURES
# ============================================================

feature_columns_from_master = [

    # Historical
    'historical_avg_demand_units',
    'historical_avg_units_dispensed',
    'historical_avg_stock_on_hand',
    'historical_avg_units_ordered',
    'historical_stockout_rate',
    'historical_avg_unit_price_inr',

    # Product
    'baseline_weekly_demand',
    'shelf_life_weeks',
    'seasonal_amplitude',
    'source_drug_category',

    # Supplier
    'source_avg_supplier_lead_time_weeks',
    'source_min_supplier_lead_time_weeks',
    'source_max_supplier_lead_time_weeks',
    'source_total_catchment_population',

    # External
    'rainfall_anomaly',
    'festival_intensity',
    'sev_dengue',
    'sev_malaria',
    'sev_flu',
    'sev_diarrhoeal',
    'sev_respiratory',
    'sev_typhoid',
    'sev_chikungunya',
    'sev_leptospirosis',
    'monsoon_phase',

    # Inventory
    'available_on_hand_quantity',
    'reserved_ratio',
    'stock_to_historical_avg_demand_ratio'
]

feature_columns_from_master = [
    col
    for col in feature_columns_from_master
    if col in df.columns
]


# ------------------------------------------------------------
# Create ONE SKU-level master row
# ------------------------------------------------------------

sku_features = (
    df[
        ['SKU'] + feature_columns_from_master
    ]
    .drop_duplicates(
        subset=['SKU']
    )
)


# ------------------------------------------------------------
# Merge SKU features
# ------------------------------------------------------------

demand_df = demand_df.merge(
    sku_features,
    on='SKU',
    how='left'
)


print(
    "\nMaster features merged."
)


# ============================================================
# 12. DC-SPECIFIC FEATURES
# ============================================================

dc_feature_columns = [

    'dc_region',

    'rainfall_anomaly',
    'festival_intensity',

    'sev_dengue',
    'sev_malaria',
    'sev_flu',
    'sev_diarrhoeal',
    'sev_respiratory',
    'sev_typhoid',
    'sev_chikungunya',
    'sev_leptospirosis',

    'monsoon_phase'
]

dc_feature_columns = [
    col
    for col in dc_feature_columns
    if col in df.columns
]


# IMPORTANT:
# We create a separate SKU/DC lookup.
# We do NOT remove SKU or DC from demand_df.

dc_lookup = (
    df[
        ['SKU', 'DC'] + dc_feature_columns
    ]
    .drop_duplicates(
        subset=['SKU', 'DC']
    )
)


# If any of these already came from SKU merge,
# remove them before DC merge to avoid _x/_y columns.

for col in dc_feature_columns:

    if col in demand_df.columns:

        demand_df.drop(
            columns=[col],
            inplace=True
        )


demand_df = demand_df.merge(
    dc_lookup,
    on=[
        'SKU',
        'DC'
    ],
    how='left'
)


print(
    "DC features merged."
)

print(
    "Current shape:",
    demand_df.shape
)


# ============================================================
# 13. GENERATE DAILY DEMAND
# ============================================================

# Historical demand
historical_demand = (
    demand_df[
        'historical_avg_demand_units'
    ]
    .astype(float)
)


# Baseline daily demand
baseline_daily = (
    demand_df[
        'baseline_weekly_demand'
    ]
    .astype(float)
    /
    7
)


# Combine historical + baseline
demand_base = (
    0.65 * historical_demand
    +
    0.35 * baseline_daily
)

demand_base = demand_base.clip(
    lower=20
)


# ------------------------------------------------------------
# Day-of-week effect
# ------------------------------------------------------------

day_of_week = (
    demand_df['date']
    .dt.dayofweek
)

weekday_effect = np.where(
    day_of_week < 5,
    1.05,
    0.90
)


# ------------------------------------------------------------
# Seasonal effect
# ------------------------------------------------------------

day_of_year = (
    demand_df['date']
    .dt.dayofyear
)

seasonal_amplitude = (
    demand_df[
        'seasonal_amplitude'
    ]
    .astype(float)
    .fillna(0.10)
)

seasonal_effect = (
    1
    +
    seasonal_amplitude
    *
    np.sin(
        2
        *
        np.pi
        *
        day_of_year
        /
        365
    )
)


# ------------------------------------------------------------
# Festival effect
# ------------------------------------------------------------

festival = (
    demand_df[
        'festival_intensity'
    ]
    .astype(float)
    .fillna(0)
)

festival_effect = (
    1
    +
    festival * 0.20
)


# ------------------------------------------------------------
# Disease effect
# ------------------------------------------------------------

disease_columns = [
    'sev_dengue',
    'sev_malaria',
    'sev_flu',
    'sev_diarrhoeal',
    'sev_respiratory',
    'sev_typhoid',
    'sev_chikungunya',
    'sev_leptospirosis'
]

existing_disease_columns = [
    col
    for col in disease_columns
    if col in demand_df.columns
]

disease_score = (
    demand_df[
        existing_disease_columns
    ]
    .fillna(0)
    .sum(axis=1)
)

disease_effect = (
    1
    +
    disease_score * 0.15
)


# ------------------------------------------------------------
# Rainfall effect
# ------------------------------------------------------------

rainfall = (
    demand_df[
        'rainfall_anomaly'
    ]
    .astype(float)
    .fillna(0)
)

rainfall_effect = (
    1
    +
    rainfall * 0.08
)


# ------------------------------------------------------------
# Random variation
# ------------------------------------------------------------

random_noise = np.random.normal(
    loc=1.0,
    scale=0.08,
    size=len(demand_df)
)


# ------------------------------------------------------------
# Actual demand
# ------------------------------------------------------------

demand_df['actual_demand'] = (

    demand_base

    *
    weekday_effect

    *
    seasonal_effect

    *
    festival_effect

    *
    disease_effect

    *
    rainfall_effect

    *
    random_noise
)


# Demand cannot be negative
demand_df['actual_demand'] = (
    demand_df[
        'actual_demand'
    ]
    .clip(lower=0)
    .round()
    .astype(int)
)


print(
    "\nDemand generated successfully!"
)

print(
    demand_df[
        [
            'date',
            'SKU',
            'DC',
            'actual_demand'
        ]
    ].head(10)
)

print(
    "\nDemand statistics:"
)

print(
    demand_df[
        'actual_demand'
    ].describe()
)


# ============================================================
# 14. SORT TIME SERIES
# ============================================================

demand_df = (
    demand_df
    .sort_values(
        [
            'SKU',
            'DC',
            'date'
        ]
    )
    .reset_index(drop=True)
)

group_cols = [
    'SKU',
    'DC'
]


# ============================================================
# 15. CALENDAR FEATURES
# ============================================================

demand_df['day_of_week'] = (
    demand_df[
        'date'
    ].dt.dayofweek
)

demand_df['day_of_month'] = (
    demand_df[
        'date'
    ].dt.day
)

demand_df['month'] = (
    demand_df[
        'date'
    ].dt.month
)

demand_df['week_of_year'] = (
    demand_df[
        'date'
    ]
    .dt.isocalendar()
    .week
    .astype(int)
)

demand_df['quarter'] = (
    demand_df[
        'date'
    ].dt.quarter
)

demand_df['is_weekend'] = (
    demand_df[
        'day_of_week'
    ] >= 5
).astype(int)


# ============================================================
# 16. LAG FEATURES
# ============================================================

demand_df['lag_1_demand'] = (
    demand_df
    .groupby(group_cols)[
        'actual_demand'
    ]
    .shift(1)
)

demand_df['lag_7_demand'] = (
    demand_df
    .groupby(group_cols)[
        'actual_demand'
    ]
    .shift(7)
)

demand_df['lag_14_demand'] = (
    demand_df
    .groupby(group_cols)[
        'actual_demand'
    ]
    .shift(14)
)


# ============================================================
# 17. ROLLING FEATURES
# ============================================================

# shift(1) is VERY IMPORTANT.
# It prevents current demand from entering the feature.

demand_df['rolling_mean_7'] = (
    demand_df
    .groupby(group_cols)[
        'actual_demand'
    ]
    .transform(
        lambda x:
        x.shift(1)
        .rolling(
            7,
            min_periods=3
        )
        .mean()
    )
)


demand_df['rolling_mean_14'] = (
    demand_df
    .groupby(group_cols)[
        'actual_demand'
    ]
    .transform(
        lambda x:
        x.shift(1)
        .rolling(
            14,
            min_periods=5
        )
        .mean()
    )
)


demand_df['rolling_std_7'] = (
    demand_df
    .groupby(group_cols)[
        'actual_demand'
    ]
    .transform(
        lambda x:
        x.shift(1)
        .rolling(
            7,
            min_periods=3
        )
        .std()
    )
)


# ============================================================
# 18. TARGETS
# ============================================================

demand_df['target_1d'] = (
    demand_df
    .groupby(group_cols)[
        'actual_demand'
    ]
    .shift(-1)
)

demand_df['target_7d'] = (
    demand_df
    .groupby(group_cols)[
        'actual_demand'
    ]
    .shift(-7)
)

demand_df['target_14d'] = (
    demand_df
    .groupby(group_cols)[
        'actual_demand'
    ]
    .shift(-14)
)


print(
    "\nFeature engineering completed!"
)

print(
    demand_df[
        [
            'date',
            'SKU',
            'DC',
            'actual_demand',
            'lag_1_demand',
            'lag_7_demand',
            'lag_14_demand',
            'rolling_mean_7',
            'rolling_mean_14',
            'target_1d',
            'target_7d',
            'target_14d'
        ]
    ].head(20)
)


# ============================================================
# 19. DEFINE FEATURES
# ============================================================

categorical_features = [
    'SKU',
    'DC',
    'source_drug_category',
    'dc_region',
    'monsoon_phase'
]

categorical_features = [
    col
    for col in categorical_features
    if col in demand_df.columns
]


numeric_features = [

    # Historical
    'historical_avg_demand_units',
    'historical_avg_units_dispensed',
    'historical_avg_stock_on_hand',
    'historical_avg_units_ordered',
    'historical_stockout_rate',
    'historical_avg_unit_price_inr',

    # Product
    'baseline_weekly_demand',
    'shelf_life_weeks',
    'seasonal_amplitude',

    # Supplier
    'source_avg_supplier_lead_time_weeks',
    'source_min_supplier_lead_time_weeks',
    'source_max_supplier_lead_time_weeks',
    'source_total_catchment_population',

    # External
    'rainfall_anomaly',
    'festival_intensity',

    'sev_dengue',
    'sev_malaria',
    'sev_flu',
    'sev_diarrhoeal',
    'sev_respiratory',
    'sev_typhoid',
    'sev_chikungunya',
    'sev_leptospirosis',

    # Inventory
    'available_on_hand_quantity',
    'reserved_ratio',
    'stock_to_historical_avg_demand_ratio',

    # Calendar
    'day_of_week',
    'day_of_month',
    'month',
    'week_of_year',
    'quarter',
    'is_weekend',

    # Time series
    'lag_1_demand',
    'lag_7_demand',
    'lag_14_demand',
    'rolling_mean_7',
    'rolling_mean_14',
    'rolling_std_7'
]

numeric_features = [
    col
    for col in numeric_features
    if col in demand_df.columns
]


print(
    "\nCategorical features:",
    len(categorical_features)
)

print(
    "Numeric features:",
    len(numeric_features)
)


# ============================================================
# 20. CREATE MODEL DATA
# ============================================================

model_df = demand_df.copy()


# Need all features and all targets
model_df = model_df.dropna(
    subset=(
        numeric_features
        +
        [
            'target_1d',
            'target_7d',
            'target_14d'
        ]
    )
).copy()


print(
    "\nRows after cleaning:",
    len(model_df)
)


# ============================================================
# 21. SAVE IDENTIFIERS BEFORE ENCODING
# ============================================================

model_df['sku_original'] = (
    model_df['SKU']
)

model_df['dc_original'] = (
    model_df['DC']
)


# ============================================================
# 22. ONE-HOT ENCODE
# ============================================================

model_df = pd.get_dummies(
    model_df,
    columns=categorical_features,
    drop_first=False
)


print(
    "Shape after encoding:",
    model_df.shape
)


# ============================================================
# 23. SORT CHRONOLOGICALLY
# ============================================================

model_df = (
    model_df
    .sort_values(
        'date'
    )
    .reset_index(drop=True)
)


# ============================================================
# 24. CHRONOLOGICAL TRAIN / TEST SPLIT
# ============================================================

split_index = int(
    len(model_df)
    *
    0.80
)

train_df = (
    model_df
    .iloc[:split_index]
    .copy()
)

test_df = (
    model_df
    .iloc[split_index:]
    .copy()
)


print(
    "\nTraining rows:",
    len(train_df)
)

print(
    "Testing rows:",
    len(test_df)
)

print(
    "\nTraining period:",
    train_df['date'].min(),
    "→",
    train_df['date'].max()
)

print(
    "Testing period:",
    test_df['date'].min(),
    "→",
    test_df['date'].max()
)


# ============================================================
# 25. SELECT FINAL MODEL COLUMNS
# ============================================================

exclude_columns = [

    # Date
    'date',
    'matched_context_date',

    # Actual/targets
    'actual_demand',
    'target_1d',
    'target_7d',
    'target_14d',

    # Text
    'product_name',
    'dc_location',
    'batch',

    # Dates
    'mfg_date',
    'receipt_date',
    'expiry_date',

    # IDs/descriptions
    'source_drug_sku',
    'drug_id',
    'source_drug_name',

    # Metadata
    'data_completion_status',

    # Object columns not encoded
    'responds_to',
    'expiry_risk',

    # Preserved identifiers
    'sku_original',
    'dc_original'
]


feature_columns = [
    col
    for col in model_df.columns
    if col not in exclude_columns
]


print(
    "\nNumber of model features:",
    len(feature_columns)
)


# ============================================================
# 26. SAFETY CHECK
# ============================================================

X_train = train_df[
    feature_columns
].copy()

X_test = test_df[
    feature_columns
].copy()


non_numeric_train = (
    X_train
    .select_dtypes(
        exclude=[
            'number',
            'bool'
        ]
    )
    .columns
    .tolist()
)

non_numeric_test = (
    X_test
    .select_dtypes(
        exclude=[
            'number',
            'bool'
        ]
    )
    .columns
    .tolist()
)


print(
    "\nNon-numeric training columns:",
    non_numeric_train
)

print(
    "Non-numeric testing columns:",
    non_numeric_test
)


if non_numeric_train:

    raise ValueError(
        "Training data still contains "
        "non-numeric columns: "
        +
        str(non_numeric_train)
    )

if non_numeric_test:

    raise ValueError(
        "Testing data still contains "
        "non-numeric columns: "
        +
        str(non_numeric_test)
    )


# ============================================================
# 27. FUNCTION TO TRAIN + EVALUATE
# ============================================================

def train_forecast_model(
    target_column,
    horizon_name
):

    print(
        "\n"
        +
        "=" * 60
    )

    print(
        f"TRAINING {horizon_name} MODEL"
    )

    print(
        "=" * 60
    )


    y_train = (
        train_df[
            target_column
        ]
        .astype(float)
    )

    y_test = (
        test_df[
            target_column
        ]
        .astype(float)
    )


    model = XGBRegressor(

        n_estimators=500,

        learning_rate=0.05,

        max_depth=6,

        min_child_weight=3,

        subsample=0.8,

        colsample_bytree=0.8,

        objective='reg:squarederror',

        random_state=42,

        n_jobs=-1
    )


    print(
        "Training XGBoost..."
    )


    model.fit(
        X_train,
        y_train
    )


    print(
        "Training completed."
    )


    predictions = model.predict(
        X_test
    )


    # Demand cannot be negative
    predictions = np.maximum(
        predictions,
        0
    )


    # --------------------------------------------------------
    # Metrics
    # --------------------------------------------------------

    mae = mean_absolute_error(
        y_test,
        predictions
    )


    rmse = np.sqrt(
        mean_squared_error(
            y_test,
            predictions
        )
    )


    # MAPE
    actual_array = y_test.values

    prediction_array = predictions

    nonzero_mask = (
        actual_array != 0
    )

    mape = (
        np.mean(
            np.abs(
                (
                    actual_array[
                        nonzero_mask
                    ]
                    -
                    prediction_array[
                        nonzero_mask
                    ]
                )
                /
                actual_array[
                    nonzero_mask
                ]
            )
        )
        *
        100
    )


    r2 = r2_score(
        y_test,
        predictions
    )


    print(
        "\nResults:"
    )

    print(
        f"MAE  : {mae:.4f}"
    )

    print(
        f"RMSE : {rmse:.4f}"
    )

    print(
        f"MAPE : {mape:.4f}%"
    )

    print(
        f"R2   : {r2:.4f}"
    )


    # --------------------------------------------------------
    # REQUIRED OUTPUT
    # --------------------------------------------------------

    prediction_output = pd.DataFrame({

        'date':
            test_df[
                'date'
            ].values,

        'sku':
            test_df[
                'sku_original'
            ].values,

        'dc':
            test_df[
                'dc_original'
            ].values,

        'actual_demand':
            y_test.values,

        'predicted_demand':
            predictions
    })


    return (
        model,
        prediction_output,
        {
            'MAE': mae,
            'RMSE': rmse,
            'MAPE': mape,
            'R2': r2
        }
    )


# ============================================================
# 28. TRAIN 1-DAY MODEL
# ============================================================

model_1d, prediction_1d, metrics_1d = (
    train_forecast_model(
        'target_1d',
        '1-DAY'
    )
)


# ============================================================
# 29. TRAIN 7-DAY MODEL
# ============================================================

model_7d, prediction_7d, metrics_7d = (
    train_forecast_model(
        'target_7d',
        '7-DAY'
    )
)


# ============================================================
# 30. TRAIN 14-DAY MODEL
# ============================================================

model_14d, prediction_14d, metrics_14d = (
    train_forecast_model(
        'target_14d',
        '14-DAY'
    )
)


[
  {
    "date": "2025-11-08",
    "sku": "SKU-0036",
    "dc": "DC-Bengaluru",
    "actual_demand": 171.0,
    "predicted_demand_1day": 164.66,
    "predicted_demand_7day": 168.42,
    "predicted_demand_14day": 172.15
  },
  {
    "date": "2025-11-08",
    "sku": "SKU-0046",
    "dc": "DC-Kolkata",
    "actual_demand": 55.0,
    "predicted_demand_1day": 55.32,
    "predicted_demand_7day": 54.81,
    "predicted_demand_14day": 56.24
  }
]

# ============================================================
# 31. DISPLAY 1-DAY PREDICTION OUTPUT
# ============================================================

print("\n")
print("=" * 70)
print("1-DAY DEMAND FORECAST")
print("=" * 70)

display(prediction_1d.head(20))


# ============================================================
# 32. CREATE COMBINED PREDICTION OUTPUT
# ============================================================

final_predictions = prediction_1d.copy()

final_predictions = final_predictions.rename(
    columns={
        'predicted_demand': 'predicted_demand_1day'
    }
)

final_predictions['predicted_demand_7day'] = (
    prediction_7d['predicted_demand'].values
)

final_predictions['predicted_demand_14day'] = (
    prediction_14d['predicted_demand'].values
)


# ============================================================
# 33. CREATE JSON OUTPUT
# ============================================================

# Convert datetime into JSON-compatible string
final_predictions['date'] = (
    pd.to_datetime(final_predictions['date'])
    .dt.strftime('%Y-%m-%d')
)


# ------------------------------------------------------------
# Select ONLY the fields required in the JSON output
# ------------------------------------------------------------

json_columns = [
    'date',
    'sku',
    'dc',
    'actual_demand',
    'predicted_demand_1day',
    'predicted_demand_7day',
    'predicted_demand_14day'
]

json_output = final_predictions[
    json_columns
].copy()


# ------------------------------------------------------------
# Round prediction values
# ------------------------------------------------------------

json_output['actual_demand'] = (
    json_output['actual_demand']
    .round(2)
)

json_output['predicted_demand_1day'] = (
    json_output['predicted_demand_1day']
    .round(2)
)

json_output['predicted_demand_7day'] = (
    json_output['predicted_demand_7day']
    .round(2)
)

json_output['predicted_demand_14day'] = (
    json_output['predicted_demand_14day']
    .round(2)
)


# ============================================================
# 34. SAVE JSON
# ============================================================

json_file = 'MedCare_Demand_Forecast_Predictions.json'

json_output.to_json(
    json_file,
    orient='records',
    indent=2
)


# ============================================================
# 35. DISPLAY JSON OUTPUT
# ============================================================

print("\n")
print("=" * 70)
print("DEMAND FORECAST JSON OUTPUT")
print("=" * 70)

# Display the JSON in the same array-of-objects style
with open(json_file, 'r', encoding='utf-8') as f:
    json_text = f.read()

print(json_text)


# ============================================================
# 36. CREATE METRICS TABLE
# ============================================================

metrics_table = pd.DataFrame({

    'horizon': [
        '1-day',
        '7-day',
        '14-day'
    ],

    'MAE': [
        metrics_1d['MAE'],
        metrics_7d['MAE'],
        metrics_14d['MAE']
    ],

    'RMSE': [
        metrics_1d['RMSE'],
        metrics_7d['RMSE'],
        metrics_14d['RMSE']
    ],

    'MAPE_percent': [
        metrics_1d['MAPE'],
        metrics_7d['MAPE'],
        metrics_14d['MAPE']
    ],

    'R2': [
        metrics_1d['R2'],
        metrics_7d['R2'],
        metrics_14d['R2']
    ]
})


print("\n")
print("=" * 70)
print("FINAL MODEL METRICS")
print("=" * 70)

display(metrics_table)


# ============================================================
# 37. SAVE EXCEL OUTPUTS
# ============================================================

prediction_1d.to_excel(
    'prediction_1day.xlsx',
    index=False
)

prediction_7d.to_excel(
    'prediction_7day.xlsx',
    index=False
)

prediction_14d.to_excel(
    'prediction_14day.xlsx',
    index=False
)

final_predictions.to_excel(
    'MedCare_Demand_Forecast_Predictions.xlsx',
    index=False
)

metrics_table.to_excel(
    'demand_forecasting_metrics.xlsx',
    index=False
)


# ============================================================
# 37.5 SAVE TO OUTPUT.DB
# ============================================================

import sqlite3
conn = sqlite3.connect('output.db')
final_predictions.to_sql('predicted_outputs', conn, if_exists='replace', index=False)
conn.close()

# ============================================================
# 38. SAVE JSON + EXCEL + DB OUTPUT SUMMARY
# ============================================================

print("\n")
print("=" * 70)
print("OUTPUT FILES SAVED")
print("=" * 70)

print("✓ prediction_1day.xlsx")
print("✓ prediction_7day.xlsx")
print("✓ prediction_14day.xlsx")
print("✓ MedCare_Demand_Forecast_Predictions.xlsx")
print("✓ MedCare_Demand_Forecast_Predictions.json")
print("✓ demand_forecasting_metrics.xlsx")

# ============================================================
# 36. SAVE COMPLETE MODEL AS ONE FILE
# ============================================================

preprocessing = {

    'feature_columns':
        feature_columns,

    'categorical_features':
        categorical_features,

    'numeric_features':
        numeric_features,

    'group_columns':
        group_cols,

    'model':
        'XGBRegressor',

    'train_test_split':
        'chronological 80/20',

    'targets': [
        'target_1d',
        'target_7d',
        'target_14d'
    ]
}


# Put all 3 trained models + preprocessing
# into ONE dictionary

MedCare_Demand_Forecasting_Model = {

    'model_1day': model_1d,

    'model_7day': model_7d,

    'model_14day': model_14d,

    'preprocessing': preprocessing
}


# Save everything into ONE .pkl file

joblib.dump(
    MedCare_Demand_Forecasting_Model,
    'MedCare_Demand_Forecasting_Model.pkl'
)


print("\n")
print("=" * 70)
print("COMPLETE MODEL SAVED")
print("=" * 70)

print("✓ MedCare_Demand_Forecasting_Model.pkl")


# ============================================================
# 37. SAVE PREPROCESSING INFORMATION
# ============================================================

preprocessing = {

    'feature_columns':
        feature_columns,

    'categorical_features':
        categorical_features,

    'numeric_features':
        numeric_features,

    'group_columns':
        group_cols,

    'model':
        'XGBRegressor',

    'train_test_split':
        'chronological 80/20',

    'targets': [
        'target_1d',
        'target_7d',
        'target_14d'
    ]
}


joblib.dump(
    preprocessing,
    'demand_forecasting_preprocessing.pkl'
)


# ============================================================
# 38. ACTUAL VS PREDICTED
# ============================================================

plt.figure(
    figsize=(14, 6)
)

plt.plot(
    prediction_1d[
        'actual_demand'
    ].values[:300],
    label='Actual'
)

plt.plot(
    prediction_1d[
        'predicted_demand'
    ].values[:300],
    label='Predicted'
)

plt.xlabel(
    'Test Observation'
)

plt.ylabel(
    'Demand'
)

plt.title(
    'XGBoost 1-Day Demand Forecast'
)

plt.legend()

plt.tight_layout()

plt.savefig(
    'actual_vs_predicted.png',
    dpi=200
)

plt.show()


# ============================================================
# 39. RESIDUAL PLOT
# ============================================================

residuals = (
    prediction_1d[
        'actual_demand'
    ]
    -
    prediction_1d[
        'predicted_demand'
    ]
)


plt.figure(
    figsize=(12, 6)
)

plt.scatter(
    prediction_1d[
        'predicted_demand'
    ],
    residuals,
    alpha=0.3
)

plt.axhline(
    0,
    linestyle='--'
)

plt.xlabel(
    'Predicted Demand'
)

plt.ylabel(
    'Residual'
)

plt.title(
    'Residual Analysis'
)

plt.tight_layout()

plt.savefig(
    'residual_analysis.png',
    dpi=200
)

plt.show()


# ============================================================
# 40. CREATE ZIP
# ============================================================

output_files = [

    'prediction_1day.xlsx',

    'prediction_7day.xlsx',

    'prediction_14day.xlsx',

    'MedCare_Demand_Forecast_Predictions.xlsx',

    'demand_forecasting_metrics.xlsx',

    'demand_feature_importance.xlsx',

    'xgboost_demand_1day.pkl',

    'xgboost_demand_7day.pkl',

    'xgboost_demand_14day.pkl',

    'demand_forecasting_preprocessing.pkl',

    'actual_vs_predicted.png',

    'residual_analysis.png'
]


zip_name = (
    'MedCare_Demand_Forecasting_Model.zip'
)


with zipfile.ZipFile(
    zip_name,
    'w',
    zipfile.ZIP_DEFLATED
) as zipf:

    for f in output_files:

        if os.path.exists(f):

            zipf.write(f)


# ============================================================
# 41. FINAL SUMMARY
# ============================================================

print("\n")
print("=" * 70)

print(
    "MEDCARE DEMAND FORECASTING COMPLETED"
)

print("=" * 70)

print(
    "\nOriginal dataset:",
    df.shape
)

print(
    "Daily dataset:",
    demand_df.shape
)

print(
    "Model dataset:",
    model_df.shape
)

print(
    "\nModels trained:"
)

print(
    "✓ 1-Day XGBoost"
)

print(
    "✓ 7-Day XGBoost"
)

print(
    "✓ 14-Day XGBoost"
)

print(
    "\nRequired prediction columns:"
)

print(
    "✓ date"
)

print(
    "✓ sku"
)

print(
    "✓ dc"
)

print(
    "✓ actual_demand"
)

print(
    "✓ predicted_demand"
)

print(
    "\nSaved:"
)

print(
    "✓ prediction_1day.xlsx"
)

print(
    "✓ prediction_7day.xlsx"
)

print(
    "✓ prediction_14day.xlsx"
)

print(
    "✓ MedCare_Demand_Forecast_Predictions.xlsx"
)

print(
    "✓ demand_forecasting_metrics.xlsx"
)

print(
    "✓ XGBoost .pkl models"
)

print(
    "✓ preprocessing .pkl"
)

print(
    "\nZIP package:"
)

print(
    zip_name
)

print("=" * 70)


# ============================================================
# 42. DOWNLOAD ZIP
# ============================================================

files.download(
    zip_name
)