from fastapi import APIRouter, Query, HTTPException
from typing import Optional
from app.services import surge_service

router = APIRouter(prefix="/surge", tags=["Surge Management"])


@router.get("/summary")
def get_surge_summary():
    """
    High-level KPI summary across all surge predictions:
    total records, surge/no-surge counts, risk-level breakdown, averages.
    """
    try:
        return surge_service.get_summary()
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/predictions")
def get_surge_predictions(
    risk_level: Optional[str] = Query(
        None,
        description="Filter by risk level: CRITICAL | HIGH | MEDIUM | LOW"
    )
):
    """
    Return all surge-scored rows from surge_predictions.csv,
    optionally filtered by risk_level.
    """
    try:
        return surge_service.get_predictions(risk_level=risk_level)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/top-products")
def get_top_surge_products():
    """
    Return the top-10 highest surge-risk products from
    top_10_surge_products.json (pre-generated by surge_train.py).
    """
    try:
        return surge_service.get_top_products()
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/model-info")
def get_surge_model_info():
    """Return basic metadata about the loaded surge XGBoost model."""
    try:
        return surge_service.get_model_info()
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
