# -*- coding: utf-8 -*-
"""expiry_risk

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_wp-wn8pasQaCdOxNL7oyZWkgduVzClI
"""

import os
import sys
import pandas as pd
import numpy as np

# Ensure display function exists when running as a standalone Python script
try:
    display
except NameError:
    def display(*args):
        for a in args:
            print(a)


# Try to upload file if in Google Colab, otherwise load local project dataset
df = None
try:
    from google.colab import files
    print("Running in Google Colab environment. Please upload file:")
    uploaded = files.upload()
    if uploaded:
        FILE_NAME = list(uploaded.keys())[0]
        df = pd.read_excel(FILE_NAME)
        print("Uploaded file:", FILE_NAME)
except Exception:
    pass

if df is None:
    # Try finding local dataset in medcare-ai
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    batches_path = os.path.join(base_dir, "data", "processed", "batches.csv")
    skus_path = os.path.join(base_dir, "data", "processed", "skus.csv")
    dcs_path = os.path.join(base_dir, "data", "processed", "dcs.csv")
    
    if os.path.exists(batches_path):
        print(f"Loading local dataset: {batches_path}")
        df = pd.read_csv(batches_path)
        
        # Standardize column names
        if 'sku_id' in df.columns: df['SKU'] = df['sku_id']
        if 'dc_id' in df.columns: df['DC'] = df['dc_id']
        if 'batch_id' in df.columns: df['batch'] = df['batch_id']
        if 'manufacturing_date' in df.columns: df['mfg_date'] = df['manufacturing_date']
        
        # Merge SKU master metadata (base_demand, name, unit_cost)
        if os.path.exists(skus_path):
            skus_df = pd.read_csv(skus_path)
            sku_map = skus_df.set_index('sku_id').to_dict('index')
            df['baseline_weekly_demand'] = df['sku_id'].map(lambda s: sku_map.get(s, {}).get('base_demand', 10.0) * 7.0)
            df['historical_avg_demand_units'] = df['sku_id'].map(lambda s: sku_map.get(s, {}).get('base_demand', 10.0))
            df['product_name'] = df['sku_id'].map(lambda s: sku_map.get(s, {}).get('name', s))
            df['unit_cost'] = df['sku_id'].map(lambda s: sku_map.get(s, {}).get('unit_cost', 10.0))
            
        # Merge DC metadata (location, region)
        if os.path.exists(dcs_path):
            dcs_df = pd.read_csv(dcs_path)
            dc_map = dcs_df.set_index('dc_id').to_dict('index')
            df['dc_location'] = df['dc_id'].map(lambda d: dc_map.get(d, {}).get('location', d))
            df['dc_region'] = df['dc_id'].map(lambda d: dc_map.get(d, {}).get('region', 'Central'))

        # Fill default columns expected by original Colab script
        df['reserved_quantity'] = 0.0
        df['on_hand_quantity'] = df['remaining_quantity']
        df['available_on_hand_quantity'] = df['remaining_quantity']

if df is None:
    raise FileNotFoundError("Could not find dataset to load.")

# Ensure all numeric columns expected by the script exist
for col in [
    'on_hand_quantity', 'reserved_quantity', 'available_on_hand_quantity',
    'historical_total_demand_units', 'historical_avg_demand_units',
    'historical_total_units_dispensed', 'historical_avg_units_dispensed',
    'historical_avg_stock_on_hand', 'historical_avg_units_ordered',
    'historical_stockout_rate', 'historical_avg_unit_price_inr',
    'baseline_weekly_demand', 'shelf_life_weeks', 'seasonal_amplitude'
]:
    if col not in df.columns:
        df[col] = 0.0

print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())



# ============================================================
# DATA CLEANING
# ============================================================

date_columns = [
    "mfg_date",
    "receipt_date",
    "expiry_date",
    "matched_context_date"
]

for col in date_columns:
    if col in df.columns:
        df[col] = pd.to_datetime(
            df[col],
            errors="coerce"
        )


numeric_columns = [
    "on_hand_quantity",
    "reserved_quantity",
    "historical_total_demand_units",
    "historical_avg_demand_units",
    "historical_total_units_dispensed",
    "historical_avg_units_dispensed",
    "historical_avg_stock_on_hand",
    "historical_avg_units_ordered",
    "historical_stockout_rate",
    "historical_avg_unit_price_inr",
    "historical_total_amount_inr",
    "historical_observation_count",
    "baseline_weekly_demand",
    "shelf_life_weeks",
    "seasonal_amplitude",
    "source_avg_supplier_lead_time_weeks",
    "source_min_supplier_lead_time_weeks",
    "source_max_supplier_lead_time_weeks",
    "source_total_catchment_population",
    "rainfall_anomaly",
    "festival_intensity",
    "sev_dengue",
    "sev_malaria",
    "sev_flu",
    "sev_diarrhoeal",
    "sev_respiratory",
    "sev_typhoid",
    "sev_chikungunya",
    "sev_leptospirosis",
    "days_from_receipt_to_expiry",
    "days_since_manufacture_at_receipt",
    "available_on_hand_quantity",
    "reserved_ratio",
    "stock_to_historical_avg_demand_ratio"
]

for col in numeric_columns:

    if col in df.columns:

        df[col] = pd.to_numeric(
            df[col],
            errors="coerce"
        )


# ------------------------------------------------------------
# Calculate available stock
# ------------------------------------------------------------

df["available_on_hand_quantity"] = (
    df["available_on_hand_quantity"]
    .fillna(
        df["on_hand_quantity"]
        - df["reserved_quantity"]
    )
    .clip(lower=0)
)


# ------------------------------------------------------------
# Remove rows without expiry date
# ------------------------------------------------------------

df = df[
    df["expiry_date"].notna()
].copy()


print("Cleaning completed.")

print("Rows:", len(df))

# ============================================================
# DAILY EXPIRY FEATURE ENGINEERING
# ============================================================

from datetime import datetime


# ------------------------------------------------------------
# Current date
# ------------------------------------------------------------

TODAY = pd.Timestamp(
    datetime.now().date()
)

print(
    "Expiry calculation date:",
    TODAY.strftime("%Y-%m-%d")
)


# ------------------------------------------------------------
# Days to expiry
# ------------------------------------------------------------

df["days_to_expiry"] = (

    df["expiry_date"]
    - TODAY

).dt.days


# ------------------------------------------------------------
# Weeks to expiry
# ------------------------------------------------------------

df["weeks_to_expiry"] = (

    df["days_to_expiry"] / 7

)


# ------------------------------------------------------------
# Expected weekly demand
# ------------------------------------------------------------

df["expected_weekly_demand"] = (
    df["baseline_weekly_demand"]
)


df["expected_weekly_demand"] = (

    df["expected_weekly_demand"]
    .fillna(
        df["historical_avg_demand_units"]
    )

)


df["expected_weekly_demand"] = (

    df["expected_weekly_demand"]
    .fillna(
        df["historical_avg_units_dispensed"]
    )

)


df["expected_weekly_demand"] = (

    df["expected_weekly_demand"]
    .fillna(0)

)


# ------------------------------------------------------------
# Expected demand during remaining shelf life
# ------------------------------------------------------------

df["expected_demand_before_expiry"] = (

    df["expected_weekly_demand"]

    * df["weeks_to_expiry"].clip(lower=0)

)


# ------------------------------------------------------------
# Expected remaining stock
# ------------------------------------------------------------

df["expected_remaining_stock"] = (

    df["available_on_hand_quantity"]

    - df["expected_demand_before_expiry"]

).clip(lower=0)


# ------------------------------------------------------------
# Expected write-off ratio
# ------------------------------------------------------------

df["expected_writeoff_ratio"] = np.where(

    df["available_on_hand_quantity"] > 0,

    df["expected_remaining_stock"]
    / df["available_on_hand_quantity"],

    0

)


df["expected_writeoff_ratio"] = (

    df["expected_writeoff_ratio"]
    .clip(0, 1)

)


display(
    df[
        [
            "SKU",
            "batch",
            "expiry_date",
            "days_to_expiry",
            "available_on_hand_quantity",
            "expected_weekly_demand",
            "expected_demand_before_expiry",
            "expected_remaining_stock",
            "expected_writeoff_ratio"
        ]
    ].head()
)

# ============================================================
# EXPIRY URGENCY
# ============================================================

def calculate_expiry_urgency(days):

    if days < 0:
        return 1.00

    elif days <= 7:
        return 1.00

    elif days <= 14:
        return 0.95

    elif days <= 30:
        return 0.85

    elif days <= 60:
        return 0.70

    elif days <= 90:
        return 0.50

    elif days <= 180:
        return 0.30

    elif days <= 365:
        return 0.15

    else:
        return 0.05


df["expiry_urgency_score"] = (

    df["days_to_expiry"]
    .apply(calculate_expiry_urgency)

)


print(
    df["expiry_urgency_score"]
    .describe()
)

# ============================================================
# INVENTORY PRESSURE
# ============================================================

df["inventory_pressure_ratio"] = np.where(

    df["expected_weekly_demand"] > 0,

    df["available_on_hand_quantity"]
    / df["expected_weekly_demand"],

    0

)


def calculate_inventory_pressure(ratio):

    if ratio >= 12:
        return 1.00

    elif ratio >= 8:
        return 0.90

    elif ratio >= 6:
        return 0.80

    elif ratio >= 4:
        return 0.65

    elif ratio >= 2:
        return 0.40

    elif ratio >= 1:
        return 0.20

    else:
        return 0.05


df["inventory_pressure_score"] = (

    df["inventory_pressure_ratio"]
    .apply(calculate_inventory_pressure)

)


display(
    df[
        [
            "SKU",
            "batch",
            "available_on_hand_quantity",
            "expected_weekly_demand",
            "inventory_pressure_ratio",
            "inventory_pressure_score"
        ]
    ].head()
)

# ============================================================
# DEMAND COVERAGE
# ============================================================

df["inventory_coverage_weeks"] = np.where(

    df["expected_weekly_demand"] > 0,

    df["available_on_hand_quantity"]
    / df["expected_weekly_demand"],

    999

)


# ------------------------------------------------------------
# Compare inventory coverage with shelf life
# ------------------------------------------------------------

df["coverage_vs_expiry_ratio"] = np.where(

    df["weeks_to_expiry"] > 0,

    df["inventory_coverage_weeks"]
    / df["weeks_to_expiry"],

    999

)


def calculate_coverage_risk(ratio):

    if ratio >= 1:
        return 1.00

    elif ratio >= 0.75:
        return 0.80

    elif ratio >= 0.50:
        return 0.60

    elif ratio >= 0.25:
        return 0.30

    else:
        return 0.05


df["coverage_risk_score"] = (

    df["coverage_vs_expiry_ratio"]
    .apply(calculate_coverage_risk)

)

# ============================================================
# FINAL EXPIRY RISK SCORE
# ============================================================

df["expiry_risk_score"] = (

    df["expiry_urgency_score"] * 0.40

    +

    df["inventory_pressure_score"] * 0.35

    +

    df["coverage_risk_score"] * 0.25

)


# ------------------------------------------------------------
# Force expired stock to maximum risk
# ------------------------------------------------------------

df.loc[
    df["days_to_expiry"] < 0,
    "expiry_risk_score"
] = 1.0


# ------------------------------------------------------------
# Keep score between 0 and 1
# ------------------------------------------------------------

df["expiry_risk_score"] = (

    df["expiry_risk_score"]
    .clip(0, 1)

)


print(
    df["expiry_risk_score"]
    .describe()
)

# ============================================================
# EXPIRY RISK CLASSIFICATION
# ============================================================

def classify_expiry_risk(row):

    score = row["expiry_risk_score"]

    days = row["days_to_expiry"]

    remaining = row["expected_remaining_stock"]

    # Already expired
    if days < 0:
        return "CRITICAL"

    # Very close to expiry and stock remains
    if days <= 30 and remaining > 0:
        return "CRITICAL"

    # High risk
    if score >= 0.75:
        return "HIGH"

    # Watch
    if score >= 0.45:
        return "WATCH"

    # Otherwise
    return "LOW"


df["expiry_risk"] = df.apply(
    classify_expiry_risk,
    axis=1
)


print(
    df["expiry_risk"]
    .value_counts()
)

# ============================================================
# EXPECTED WRITE-OFF QUANTITY
# ============================================================

df["expected_writeoff_quantity"] = (

    df["available_on_hand_quantity"]

    * df["expiry_risk_score"]

)


df["expected_writeoff_quantity"] = (

    df["expected_writeoff_quantity"]
    .round()
    .astype(int)

)


# Never allow write-off quantity above inventory

df["expected_writeoff_quantity"] = np.minimum(

    df["expected_writeoff_quantity"],

    df["available_on_hand_quantity"]

)


display(
    df[
        [
            "SKU",
            "batch",
            "available_on_hand_quantity",
            "expiry_risk_score",
            "expiry_risk",
            "expected_writeoff_quantity"
        ]
    ].head(20)
)

# ============================================================
# EXPIRY-AWARE ALLOCATION PRIORITY
# ============================================================

risk_priority = {

    "CRITICAL": 1,

    "HIGH": 2,

    "WATCH": 3,

    "LOW": 4

}


df["allocation_priority"] = (

    df["expiry_risk"]
    .map(risk_priority)

)


# ------------------------------------------------------------
# Within same risk:
# earliest expiry comes first
# ------------------------------------------------------------

df = df.sort_values(

    by=[
        "SKU",
        "DC",
        "allocation_priority",
        "expiry_date"
    ],

    ascending=[
        True,
        True,
        True,
        True
    ]

)


display(
    df[
        [
            "SKU",
            "DC",
            "batch",
            "expiry_date",
            "days_to_expiry",
            "available_on_hand_quantity",
            "expiry_risk",
            "expiry_risk_score",
            "allocation_priority"
        ]
    ].head(30)
)

# ============================================================
# RECOMMENDED ACTION
# ============================================================

def get_action(row):

    risk = row["expiry_risk"]

    days = row["days_to_expiry"]

    remaining = row["expected_remaining_stock"]

    if days < 0:

        return "EXPIRED_STOCK"

    elif risk == "CRITICAL":

        return "URGENT_ALLOCATION"

    elif risk == "HIGH":

        return "PRIORITIZE_ALLOCATION"

    elif risk == "WATCH":

        return "PRIORITIZE_ALLOCATION"

    else:

        return "NORMAL_ALLOCATION"


df["recommended_action"] = df.apply(
    get_action,
    axis=1
)


print(
    df["recommended_action"]
    .value_counts()
)

# ============================================================
# FINAL OUTPUT
# ============================================================

output_columns = [

    "SKU",
    "product_name",
    "DC",
    "dc_location",
    "batch",

    "mfg_date",
    "receipt_date",
    "expiry_date",

    "on_hand_quantity",
    "reserved_quantity",
    "available_on_hand_quantity",

    "baseline_weekly_demand",
    "historical_avg_demand_units",
    "historical_avg_units_dispensed",

    "days_to_expiry",
    "weeks_to_expiry",

    "expected_weekly_demand",

    "expected_demand_before_expiry",

    "expected_remaining_stock",

    "inventory_coverage_weeks",

    "expiry_urgency_score",
    "inventory_pressure_score",
    "coverage_risk_score",

    "expiry_risk_score",

    "expected_writeoff_quantity",

    "expiry_risk",

    "allocation_priority",

    "recommended_action"
]


output_columns = [

    col

    for col in output_columns

    if col in df.columns

]


expiry_output = df[
    output_columns
].copy()


print(
    "Final expiry output shape:",
    expiry_output.shape
)


display(
    expiry_output.head(20)
)

# ============================================================
# EXPIRY SUMMARY
# ============================================================

print("=" * 70)
print("EXPIRY RISK SUMMARY")
print("=" * 70)

print("\nRisk distribution:")

print(
    expiry_output[
        "expiry_risk"
    ].value_counts()
)


print("\nTotal available inventory:")

print(
    expiry_output[
        "available_on_hand_quantity"
    ].sum()
)


print("\nExpected write-off quantity:")

print(
    expiry_output[
        "expected_writeoff_quantity"
    ].sum()
)


print("\nRisk by SKU:")

risk_by_sku = (

    expiry_output
    .groupby(
        "SKU"
    )
    .agg(

        total_stock=(
            "available_on_hand_quantity",
            "sum"
        ),

        expected_writeoff=(
            "expected_writeoff_quantity",
            "sum"
        ),

        highest_risk=(
            "expiry_risk_score",
            "max"
        )

    )
    .sort_values(
        "expected_writeoff",
        ascending=False
    )

)

display(
    risk_by_sku.head(20)
)

# ============================================================
# SAVE EXCEL
# ============================================================

OUTPUT_EXCEL = "expiry_predictions.xlsx"

expiry_output.to_excel(
    OUTPUT_EXCEL,
    index=False
)

print(
    "Saved:",
    OUTPUT_EXCEL
)

# ============================================================
# SAVE JSON
# ============================================================

import json

json_output = expiry_output.copy()


# Convert dates

for col in [
    "mfg_date",
    "receipt_date",
    "expiry_date"
]:

    if col in json_output.columns:

        json_output[col] = (

            json_output[col]
            .dt.strftime("%Y-%m-%d")

        )


# Convert NaN to None

json_output = (
    json_output
    .replace({np.nan: None})
)


records = json_output.to_dict(
    orient="records"
)


with open(
    "expiry_predictions.json",
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        records,
        file,
        indent=2,
        ensure_ascii=False
    )


print(
    "Saved: expiry_predictions.json"
)

import json

expiry_model_weights = {
    "model_name": "Expiry Aware Allocation Model",
    "model_type": "Weighted Risk Scoring",
    "weights": {
        "expiry_urgency_score": 0.40,
        "inventory_pressure_score": 0.35,
        "coverage_risk_score": 0.25
    },
    "formula": (
        "0.40 * expiry_urgency_score + "
        "0.35 * inventory_pressure_score + "
        "0.25 * coverage_risk_score"
    )
}

with open(
    "expiry_model_weights.json",
    "w"
) as f:
    json.dump(
        expiry_model_weights,
        f,
        indent=4
    )

print("Saved: expiry_model_weights.json")

# Safe download for Google Colab
try:
    from google.colab import files
    files.download("expiry_model_weights.json")
except Exception:
    pass